# Generated by Django 4.0.1 on 2022-01-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0004_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
